name: qa plan and apply

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:

  qa-plan:
    uses: ./.github/workflows/terraform_common.yml
    with:
      action: "plan"
      tf_var_file: "qa.tfvars"

  qa-apply:
    needs: qa-plan
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest  
    environment: qa
    
    steps:
      - name: apple qa tf
        uses: ./.github/workflows/terraform_common.yml
        with:
          action: "apply"
          tf_var_file: "qa.tfvars"