name: qa plan and apply

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master


jobs:
  qa-plan:
    uses: ./github/workflows/terraform_common.yml
    with:
      action: "plan"
      tf_var_file: "qa.tfvars"


  qa-apply:
    needs: qa-plan
    enviornment: qa
    if: github.event_name == "push"
    uses: ./github/workflows/terraform_common.yml
    with:
      action: "apply"
      tf_var_file: "qa.tfvars"
