name: qa plan and apply

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:

  qa-plan:
    uses: akshu78602/cat-blog/.github/workflows/terraform_commons.yml@master
    with:
      action: "plan"
      tf_var_file: "environments/qa.tfvars"

  qa-apply:
    needs: qa-plan
    if: ${{ github.event_name == 'push' }}
    uses: akshu78602/cat-blog/.github/workflows/terraform_commons.yml@master
    with:
      action: "apply"
      tf_var_file: "qa.tfvars"
