name: qa plan and apply

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:

  qa-plan:
    uses: ./.github/workflows/terraform_commons.yml
    with:
      action: "plan"
      tf_var_file: "environments/qa.tfvars"

  qa-apply:
    needs: qa-plan
    environment: qa
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/terraform_commons.yml
    with:
      action: "apply"
      tf_var_file: "environments/qa.tfvars"
